setwd("C:/Users/jazmi/Downloads")
datos <- read.csv("unity.csv")

##Debido a que en su momento se descargaron todos los datos
##incluidos basicos preprimarias etc, se quitan para dejar solo diversificado

datos <- datos[!grepl("BASICO", datos$NIVEL),]
datos <-datos[!grepl("PRIMARIA", datos$NIVEL),]
datos <-datos[!grepl("PREPRIMARIA BILINGUE", datos$NIVEL),]
datos <-datos[!grepl("PARVULOS", datos$NIVEL),]
datos <-datos[grepl("DIVERSIFICADO", datos$NIVEL),]

##Para las columnas con filas en blanco, se sustityue el blanco por Nao por 0 
datos$DISTRITO <- sub("^$", NA, datos$DISTRITO)
datos$DIRECTOR <- sub("^$", NA, datos$DIRECTOR)
datos$SUPERVISOR <- sub("^$", NA, datos$SUPERVISOR)
datos$DIRECCION<- sub("^$", NA, datos$DIRECCION)
datos$TELEFONO<- sub("^$", 0, datos$TELEFONO)

##Status a numeros
## Abierto = 1
##Cerrada Temporalmente = 2
##Temporal contrato 021 =3
##temporal nombramiento = 4
##temporal titulos = 5
datos$STATUS <- as.character(datos$STATUS)
datos$STATUS[datos$STATUS == "ABIERTA"] <- 1
datos$STATUS[datos$STATUS == "CERRADA TEMPORALMENTE"] <- 2
datos$STATUS[datos$STATUS == "TEMPORAL CONTRATO 021"] <- 3
datos$STATUS[datos$STATUS == "TEMPORAL NOMBRAMIENTO"] <- 4
datos$STATUS[datos$STATUS == "TEMPORAL TITULOS"] <- 5
datos$STATUS<- factor(datos$STATUS)

##departamentos a numeros segun la guia referenciada en el trabajo escrito
##Esto se hace para poder tener una mejor forma de manjear los datos
datos$DEPARTAMENTO <- as.character(datos$DEPARTAMENTO)
datos$DEPARTAMENTO[datos$DEPARTAMENTO == "CIUDAD CAPITAL"] <- 0
datos$DEPARTAMENTO[datos$DEPARTAMENTO == "GUATEMALA"] <- 1
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="EL PROGRESO"] <- 2
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="SACATEPEQUEZ"] <- 3
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="CHIMALTENANGO"] <- 4
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="ESCUINTLA"] <- 5
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="SANTA ROSA"] <- 6
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="SOLOLA"] <- 7
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="TOTONICAPAN"] <- 8
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="QUETZALTENANGO"] <- 9
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="SUCHITEPEQUEZ"] <- 10
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="RETALHULEU"] <- 11
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="SAN MARCOS"] <- 12
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="HUEHUETENANGO"] <-13
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="QUICHE"] <- 14
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="BAJA VERAPAZ"] <- 15
datos$DEPARTAMENTO[datos$DEPARTAMENTO == "ALTA VERAPAZ" ] <-16
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="PETEN"] <- 17
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="IZABAL"] <- 18
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="ZACAPA"] <- 19
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="CHIQUIMULA"] <- 20
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="JALAPA"] <- 21
datos$DEPARTAMENTO[datos$DEPARTAMENTO =="JUTIAPA"] <- 22
datos$DEPARTAMENTO <- factor(datos$DEPARTAMENTO)

# Municipios a codigos segun la guia referenciada en el trabajo escrito
##Esto se hace para poder tener una mejor forma de manjear los datos
datos$MUNICIPIO <- as.character(datos$MUNICIPIO)
datos$MUNICIPIO[datos$MUNICIPIO == "GUATEMALA"] <-0101
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CATARINA PINULA"] <-0102
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE PINULA"] <-0103
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE DEL GOLFO"] <-0104
datos$MUNICIPIO[datos$MUNICIPIO == "PALENCIA"] <-0105
datos$MUNICIPIO[datos$MUNICIPIO == "CHINAUTLA"] <-0106
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO AYAMPUC"] <-0107
datos$MUNICIPIO[datos$MUNICIPIO == "MIXCO"] <-0108
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO SACATEPEQUEZ"] <-0109
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN SACATEPEQUEZ"] <-0110
datos$MUNICIPIO[datos$MUNICIPIO == "SAN RAYMUNDO"] <-0111
datos$MUNICIPIO[datos$MUNICIPIO == "CHUARRANCHO"] <-0112
datos$MUNICIPIO[datos$MUNICIPIO == "FRAIJANES"] <-0113
datos$MUNICIPIO[datos$MUNICIPIO == "AMATITLAN"] <-0114
datos$MUNICIPIO[datos$MUNICIPIO == "VILLA NUEVA"] <-0115
datos$MUNICIPIO[datos$MUNICIPIO == "VILLA CANALES"] <-0116
datos$MUNICIPIO[datos$MUNICIPIO == "PETAPA"] <-0117
datos$MUNICIPIO[datos$MUNICIPIO == "GUASTATOYA"] <-0201
datos$MUNICIPIO[datos$MUNICIPIO == "MORAZAN"] <-0202
datos$MUNICIPIO[datos$MUNICIPIO == "SAN AGUSTIN ACASAGUASTLAN"] <-0203
datos$MUNICIPIO[datos$MUNICIPIO == "SAN CRISTOBAL ACASAGUASTLAN"] <-0204
datos$MUNICIPIO[datos$MUNICIPIO == "EL JICARO"] <-0205
datos$MUNICIPIO[datos$MUNICIPIO == "SANSARE"] <-0206
datos$MUNICIPIO[datos$MUNICIPIO == "SANARATE"] <-0207
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANTONIO LA PAZ"] <-0208
datos$MUNICIPIO[datos$MUNICIPIO == "ANTIGUA GUATEMALA"] <-0301
datos$MUNICIPIO[datos$MUNICIPIO == "JOCOTENANGO"] <-0302
datos$MUNICIPIO[datos$MUNICIPIO == "PASTORES"] <-0303
datos$MUNICIPIO[datos$MUNICIPIO == "SUMPANGO"] <-0304
datos$MUNICIPIO[datos$MUNICIPIO == "SANTO DOMINGO XENACOJ"] <-0305
datos$MUNICIPIO[datos$MUNICIPIO == "SANTIAGO SACATEPEQUEZ"] <-0306
datos$MUNICIPIO[datos$MUNICIPIO == "SAN BARTOLOME MILPAS ALTAS"] <-0307
datos$MUNICIPIO[datos$MUNICIPIO == "SAN LUCAS SACATEPEQUEZ"] <-0308
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA LUCIA MILPAS ALTAS"] <-0309
datos$MUNICIPIO[datos$MUNICIPIO == "MAGDALENA MILPAS ALTAS"] <-0310
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA MARIA DE JESUS"] <-0311
datos$MUNICIPIO[datos$MUNICIPIO == "CIUDAD VIEJA"] <-0312
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL DUE?AS"] <-0313
datos$MUNICIPIO[datos$MUNICIPIO == "ALOTENANGO"] <-0314
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANTONIO AGUAS CALIENTES"] <-0315
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CATARINA BARAHONA"] <-0316
datos$MUNICIPIO[datos$MUNICIPIO == "CHIMALTENANGO"] <-0401
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE POAQUIL"] <-0402
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MARTIN JILOTEPEQUE"] <-0403
datos$MUNICIPIO[datos$MUNICIPIO == "COMALAPA"] <-0404
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA APOLONIA"] <-0405
datos$MUNICIPIO[datos$MUNICIPIO == "TECPAN GUATEMALA"] <-0406
datos$MUNICIPIO[datos$MUNICIPIO == "PATZUN"] <-0407
datos$MUNICIPIO[datos$MUNICIPIO == "POCHUTA"] <-0408
datos$MUNICIPIO[datos$MUNICIPIO == "PATZICIA"] <-0409
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CRUZ BALANYA"] <-0410
datos$MUNICIPIO[datos$MUNICIPIO == "ACATENANGO"] <-0411
datos$MUNICIPIO[datos$MUNICIPIO == "YEPOCAPA"] <-0412
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANDRES ITZAPA"] <-0413
datos$MUNICIPIO[datos$MUNICIPIO == "PARRAMOS"] <-0414
datos$MUNICIPIO[datos$MUNICIPIO == "ZARAGOZA"] <-0415
datos$MUNICIPIO[datos$MUNICIPIO == "EL TEJAR"] <-0416
datos$MUNICIPIO[datos$MUNICIPIO == "ESCUINTLA"] <-0501
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA LUCIA COTZUMALGUAPA"] <-0502
datos$MUNICIPIO[datos$MUNICIPIO == "LA DEMOCRACIA"] <-0503
datos$MUNICIPIO[datos$MUNICIPIO == "SIQUINALA"] <-0504
datos$MUNICIPIO[datos$MUNICIPIO == "MASAGUA"] <-0505
datos$MUNICIPIO[datos$MUNICIPIO == "TIQUISATE"] <-0506
datos$MUNICIPIO[datos$MUNICIPIO == "LA GOMERA"] <-0507
datos$MUNICIPIO[datos$MUNICIPIO == "GUANAGAZAPA"] <-0508
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE"] <-0509
datos$MUNICIPIO[datos$MUNICIPIO == "IZTAPA"] <-0510
datos$MUNICIPIO[datos$MUNICIPIO == "PALIN"] <-0511
datos$MUNICIPIO[datos$MUNICIPIO == "SAN VICENTE PACAYA"] <-0512
datos$MUNICIPIO[datos$MUNICIPIO == "NUEVA CONCEPCION"] <-0513
datos$MUNICIPIO[datos$MUNICIPIO == "CUILAPA"] <-0601
datos$MUNICIPIO[datos$MUNICIPIO == "BARBERENA"] <-0602
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA ROSA DE LIMA"] <-0603
datos$MUNICIPIO[datos$MUNICIPIO == "CASILLAS"] <-0604
datos$MUNICIPIO[datos$MUNICIPIO == "SAN RAFAEL LAS FLORES"] <-0605
datos$MUNICIPIO[datos$MUNICIPIO == "ORATORIO"] <-0606
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN TECUACO"] <-0607
datos$MUNICIPIO[datos$MUNICIPIO == "CHIQUIMULILLA"] <-0608
datos$MUNICIPIO[datos$MUNICIPIO == "TAXISCO"] <-0609
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA MARIA IXHUATAN"] <-0610
datos$MUNICIPIO[datos$MUNICIPIO == "GUAZACAPAN"] <-0611
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CRUZ NARANJO"] <-0612
datos$MUNICIPIO[datos$MUNICIPIO == "PUEBLO NUEVO VI?AS"] <-0613
datos$MUNICIPIO[datos$MUNICIPIO == "NUEVA SANTA ROSA"] <-0614
datos$MUNICIPIO[datos$MUNICIPIO == "SOLOLA"] <-0701
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE CHACAYA"] <-0702
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA MARIA VISITACION"] <-0703
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA LUCIA UTATLAN"] <-0704
datos$MUNICIPIO[datos$MUNICIPIO == "NAHUALA"] <-0705
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CATARINA IXTAHUACAN"] <-0706
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CLARA LA LAGUNA"] <-0707
datos$MUNICIPIO[datos$MUNICIPIO == "CONCEPCION"] <-0708
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANDRES SEMETABAJ"] <-0709
datos$MUNICIPIO[datos$MUNICIPIO == "PANAJACHEL"] <-0710
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CATARINA PALOPO"] <-0711
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANTONIO PALOPO"] <-0712
datos$MUNICIPIO[datos$MUNICIPIO == "SAN LUCAS TOLIMAN"] <-0713
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CRUZ LA LAGUNA"] <-0714
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PABLO LA LAGUNA"] <-0715
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MARCOS LA LAGUNA"] <-0716
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN LA LAGUNA"] <-0717
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO LA LAGUNA"] <-0718
datos$MUNICIPIO[datos$MUNICIPIO == "SANTIAGO ATITLAN"] <-0719
datos$MUNICIPIO[datos$MUNICIPIO == "TOTONICAPAN"] <-0801
datos$MUNICIPIO[datos$MUNICIPIO == "SAN CRISTOBAL TOTONICAPAN"] <-0802
datos$MUNICIPIO[datos$MUNICIPIO == "SAN FRANCISCO EL ALTO"] <-0803
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANDRES XECUL"] <-0804
datos$MUNICIPIO[datos$MUNICIPIO == "MOMOSTENANGO"] <-0805
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA MARIA CHIQUIMULA"] <-0806
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA LUCIA LA REFORMA"] <-0807
datos$MUNICIPIO[datos$MUNICIPIO == "SAN BARTOLO"] <-0808
datos$MUNICIPIO[datos$MUNICIPIO == "QUETZALTENANGO"] <-0901
datos$MUNICIPIO[datos$MUNICIPIO == "SALCAJA"] <-0902
datos$MUNICIPIO[datos$MUNICIPIO == "OLINTEPEQUE"] <-0903
datos$MUNICIPIO[datos$MUNICIPIO == "SAN CARLOS SIJA"] <-0904
datos$MUNICIPIO[datos$MUNICIPIO == "SIBILIA"] <-0905
datos$MUNICIPIO[datos$MUNICIPIO == "CABRICAN"] <-0906
datos$MUNICIPIO[datos$MUNICIPIO == "CAJOLA"] <-0907
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL SIGUILA"] <-0908
datos$MUNICIPIO[datos$MUNICIPIO == "OSTUNCALCO"] <-0909
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MATEO"] <-0910
datos$MUNICIPIO[datos$MUNICIPIO == "CONCEPCION CHIQUIRICHAPA"] <-0911
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MARTIN SACATEPEQUEZ"] <-0912
datos$MUNICIPIO[datos$MUNICIPIO == "ALMOLONGA"] <-0913
datos$MUNICIPIO[datos$MUNICIPIO == "CANTEL"] <-0914
datos$MUNICIPIO[datos$MUNICIPIO == "HUITAN"] <-0915
datos$MUNICIPIO[datos$MUNICIPIO == "ZUNIL"] <-0916
datos$MUNICIPIO[datos$MUNICIPIO == "COLOMBA"] <-0917
datos$MUNICIPIO[datos$MUNICIPIO == "SAN FRANCISCO LA UNION"] <-0918
datos$MUNICIPIO[datos$MUNICIPIO == "EL PALMAR"] <-0919
datos$MUNICIPIO[datos$MUNICIPIO == "COATEPEQUE"] <-0920
datos$MUNICIPIO[datos$MUNICIPIO == "GENOVA"] <-0921
datos$MUNICIPIO[datos$MUNICIPIO == "FLORES COSTA CUCA"] <-0922
datos$MUNICIPIO[datos$MUNICIPIO == "LA ESPERANZA"] <-0923
datos$MUNICIPIO[datos$MUNICIPIO == "PALESTINA DE LOS ALTOS"] <-0924
datos$MUNICIPIO[datos$MUNICIPIO == "MAZATENANGO"] <-1001
datos$MUNICIPIO[datos$MUNICIPIO == "CUYOTENANGO"] <-1002
datos$MUNICIPIO[datos$MUNICIPIO == "SAN FRANCISCO ZAPOTITLAN"] <-1003
datos$MUNICIPIO[datos$MUNICIPIO == "SAN BERNARDINO"] <-1004
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE EL IDOLO"] <-1005
datos$MUNICIPIO[datos$MUNICIPIO == "SANTO DOMINGO SUCHITEPEQUEZ"] <-1006
datos$MUNICIPIO[datos$MUNICIPIO == "SAN LORENZO"] <-1007
datos$MUNICIPIO[datos$MUNICIPIO == "SAMAYAC"] <-1008
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PABLO JOCOPILAS"] <-1009
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANTONIO SUCHITEPEQUEZ"] <-1010
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL PANAN"] <-1011
datos$MUNICIPIO[datos$MUNICIPIO == "SAN GABRIEL"] <-1012
datos$MUNICIPIO[datos$MUNICIPIO == "CHICACAO"] <-1013
datos$MUNICIPIO[datos$MUNICIPIO == "PATULUL"] <-1014
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA BARBARA"] <-1015
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN BAUTISTA"] <-1016
datos$MUNICIPIO[datos$MUNICIPIO == "SANTO TOMAS LA UNION"] <-1017
datos$MUNICIPIO[datos$MUNICIPIO == "ZUNILITO"] <-1018
datos$MUNICIPIO[datos$MUNICIPIO == "PUEBLO NUEVO"] <-1019
datos$MUNICIPIO[datos$MUNICIPIO == "RIO BRAVO"] <-1020
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE LA MAQUINA"] <-1021
datos$MUNICIPIO[datos$MUNICIPIO == "RETALHULEU"] <-1101
datos$MUNICIPIO[datos$MUNICIPIO == "SAN SEBASTIAN"] <-1102
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CRUZ MULUA"] <-1103
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MARTIN ZAPOTITLAN"] <-1104
datos$MUNICIPIO[datos$MUNICIPIO == "SAN FELIPE"] <-1105
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANDRES VILLA SECA"] <-1106
datos$MUNICIPIO[datos$MUNICIPIO == "CHAMPERICO"] <-1107
datos$MUNICIPIO[datos$MUNICIPIO == "NUEVO SAN CARLOS"] <-1108
datos$MUNICIPIO[datos$MUNICIPIO == "EL ASINTAL"] <-1109
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MARCOS"] <-1201
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO SACATEPEQUEZ"] <-1202
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANTONIO SACATEPEQUEZ"] <-1203
datos$MUNICIPIO[datos$MUNICIPIO == "COMITANCILLO"] <-1204
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL IXTAHUACAN"] <-1205
datos$MUNICIPIO[datos$MUNICIPIO == "CONCEPCION TUTUAPA"] <-1206
datos$MUNICIPIO[datos$MUNICIPIO == "TACANA"] <-1207
datos$MUNICIPIO[datos$MUNICIPIO == "SIBINAL"] <-1208
datos$MUNICIPIO[datos$MUNICIPIO == "TAJUMULCO"] <-1209
datos$MUNICIPIO[datos$MUNICIPIO == "TEJUTLA"] <-1210
datos$MUNICIPIO[datos$MUNICIPIO == "SAN RAFAEL PIE DE LA CUESTA"] <-1211
datos$MUNICIPIO[datos$MUNICIPIO == "NUEVO PROGRESO"] <-1212
datos$MUNICIPIO[datos$MUNICIPIO == "EL TUMBADOR"] <-1213
datos$MUNICIPIO[datos$MUNICIPIO == "EL RODEO"] <-1214
datos$MUNICIPIO[datos$MUNICIPIO == "MALACATAN"] <-1215
datos$MUNICIPIO[datos$MUNICIPIO == "CATARINA"] <-1216
datos$MUNICIPIO[datos$MUNICIPIO == "AYUTLA"] <-1217
datos$MUNICIPIO[datos$MUNICIPIO == "OCOS"] <-1218
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PABLO"] <-1219
datos$MUNICIPIO[datos$MUNICIPIO == "EL QUETZAL"] <-1220
datos$MUNICIPIO[datos$MUNICIPIO == "LA REFORMA"] <-1221
datos$MUNICIPIO[datos$MUNICIPIO == "PAJAPITA"] <-1222
datos$MUNICIPIO[datos$MUNICIPIO == "IXCHIGUAN"] <-1223
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE OJETENAN"] <-1224
datos$MUNICIPIO[datos$MUNICIPIO == "SAN CRISTOBAL CUCHO"] <-1225
datos$MUNICIPIO[datos$MUNICIPIO == "SIPACAPA"] <-1226
datos$MUNICIPIO[datos$MUNICIPIO == "ESQUIPULAS PALO GORDO"] <-1227
datos$MUNICIPIO[datos$MUNICIPIO == "RIO BLANCO"] <-1228
datos$MUNICIPIO[datos$MUNICIPIO == "SAN LORENZO"] <-1229
datos$MUNICIPIO[datos$MUNICIPIO == "LA BLANCA"] <-1230
datos$MUNICIPIO[datos$MUNICIPIO == "HUEHUETENANGO"] <-1301
datos$MUNICIPIO[datos$MUNICIPIO == "CHIANTLA"] <-1302
datos$MUNICIPIO[datos$MUNICIPIO == "MALACATANCITO"] <-1303
datos$MUNICIPIO[datos$MUNICIPIO == "CUILCO"] <-1304
datos$MUNICIPIO[datos$MUNICIPIO == "NENTON"] <-1305
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO NECTA"] <-1306
datos$MUNICIPIO[datos$MUNICIPIO == "JACALTENANGO"] <-1307
datos$MUNICIPIO[datos$MUNICIPIO == "SOLOMA"] <-1308
datos$MUNICIPIO[datos$MUNICIPIO == "IXTAHUACAN"] <-1309
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA BARBARA"] <-1310
datos$MUNICIPIO[datos$MUNICIPIO == "LA LIBERTAD"] <-1311
datos$MUNICIPIO[datos$MUNICIPIO == "LA DEMOCRACIA"] <-1312
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL ACATAN"] <-1313
datos$MUNICIPIO[datos$MUNICIPIO == "SAN RAFAEL LA INDEPENDENCIA"] <-1314
datos$MUNICIPIO[datos$MUNICIPIO == "TODOS SANTOS CUCHUMATAN"] <-1315
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN ATITAN"] <-1316
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA EULALIA"] <-1317
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MATEO IXTATAN"] <-1318
datos$MUNICIPIO[datos$MUNICIPIO == "COLOTENANGO"] <-1319
datos$MUNICIPIO[datos$MUNICIPIO == "SAN SEBASTIAN HUEHUETENANGO"] <-1320
datos$MUNICIPIO[datos$MUNICIPIO == "TECTITAN"] <-1321
datos$MUNICIPIO[datos$MUNICIPIO == "CONCEPCION HUISTA"] <-1322
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN IXCOY"] <-1323
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANTONIO HUISTA"] <-1324
datos$MUNICIPIO[datos$MUNICIPIO == "SAN SEBASTIAN COATAN"] <-1325
datos$MUNICIPIO[datos$MUNICIPIO == "BARILLAS"] <-1326
datos$MUNICIPIO[datos$MUNICIPIO == "AGUACATAN"] <-1327
datos$MUNICIPIO[datos$MUNICIPIO == "SAN RAFAEL PETZAL"] <-1328
datos$MUNICIPIO[datos$MUNICIPIO == "SAN GASPAR IXCHIL"] <-1329
datos$MUNICIPIO[datos$MUNICIPIO == "SANTIAGO CHIMALTENANGO"] <-1330
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA ANA HUISTA"] <-1331
datos$MUNICIPIO[datos$MUNICIPIO == "UNION CANTINIL"] <-1332
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CRUZ DEL QUICHE"] <-1401
datos$MUNICIPIO[datos$MUNICIPIO == "CHICHE"] <-1402
datos$MUNICIPIO[datos$MUNICIPIO == "CHINIQUE"] <-1403
datos$MUNICIPIO[datos$MUNICIPIO == "ZACUALPA"] <-1404
datos$MUNICIPIO[datos$MUNICIPIO == "CHAJUL"] <-1405
datos$MUNICIPIO[datos$MUNICIPIO == "CHICHICASTENANGO"] <-1406
datos$MUNICIPIO[datos$MUNICIPIO == "PATZITE"] <-1407
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANTONIO ILOTENANGO"] <-1408
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO JOCOPILAS"] <-1409
datos$MUNICIPIO[datos$MUNICIPIO == "CUNEN"] <-1410
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN COTZAL"] <-1411
datos$MUNICIPIO[datos$MUNICIPIO == "JOYABAJ"] <-1412
datos$MUNICIPIO[datos$MUNICIPIO == "NEBAJ"] <-1413
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANDRES SAJCABAJA"] <-1414
datos$MUNICIPIO[datos$MUNICIPIO == "USPANTAN"] <-1415
datos$MUNICIPIO[datos$MUNICIPIO == "SACAPULAS"] <-1416
datos$MUNICIPIO[datos$MUNICIPIO == "SAN BARTOLOME JOCOTENANGO"] <-1417
datos$MUNICIPIO[datos$MUNICIPIO == "CANILLA"] <-1418
datos$MUNICIPIO[datos$MUNICIPIO == "CHICAMAN"] <-1419
datos$MUNICIPIO[datos$MUNICIPIO == "IXCAN"] <-1420
datos$MUNICIPIO[datos$MUNICIPIO == "PACHALUM"] <-1421
datos$MUNICIPIO[datos$MUNICIPIO == "SALAMA"] <-1501
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL CHICAJ"] <-1502
datos$MUNICIPIO[datos$MUNICIPIO == "RABINAL"] <-1503
datos$MUNICIPIO[datos$MUNICIPIO == "CUBULCO"] <-1504
datos$MUNICIPIO[datos$MUNICIPIO == "GRANADOS"] <-1505
datos$MUNICIPIO[datos$MUNICIPIO == "EL CHOL"] <-1506
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JERONIMO"] <-1507
datos$MUNICIPIO[datos$MUNICIPIO == "PURULHA"] <-1508
datos$MUNICIPIO[datos$MUNICIPIO == "COBAN"] <-1601
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CRUZ VERAPAZ"] <-1602
datos$MUNICIPIO[datos$MUNICIPIO == "SAN CRISTOBAL VERAPAZ"] <-1603
datos$MUNICIPIO[datos$MUNICIPIO == "TACTIC"] <-1604
datos$MUNICIPIO[datos$MUNICIPIO == "TAMAHU"] <-1605
datos$MUNICIPIO[datos$MUNICIPIO == "TUCURU"] <-1606
datos$MUNICIPIO[datos$MUNICIPIO == "PANZOS"] <-1607
datos$MUNICIPIO[datos$MUNICIPIO == "SENAHU"] <-1608
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO CARCHA"] <-1609
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN CHAMELCO"] <-1610
datos$MUNICIPIO[datos$MUNICIPIO == "LANQUIN"] <-1611
datos$MUNICIPIO[datos$MUNICIPIO == "CAHABON"] <-1612
datos$MUNICIPIO[datos$MUNICIPIO == "CHISEC"] <-1613
datos$MUNICIPIO[datos$MUNICIPIO == "CHAHAL"] <-1614
datos$MUNICIPIO[datos$MUNICIPIO == "FRAY BARTOLOME DE LAS CASAS"] <-1615
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CATALINA LA TINTA"] <-1616
datos$MUNICIPIO[datos$MUNICIPIO == "RAXRUHA"] <-1617
datos$MUNICIPIO[datos$MUNICIPIO == "FLORES"] <-1701
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE"] <-1702
datos$MUNICIPIO[datos$MUNICIPIO == "SAN BENITO"] <-1703
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ANDRES"] <-1704
datos$MUNICIPIO[datos$MUNICIPIO == "LA LIBERTAD"] <-1705
datos$MUNICIPIO[datos$MUNICIPIO == "SAN FRANCISCO"] <-1706
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA ANA"] <-1707
datos$MUNICIPIO[datos$MUNICIPIO == "DOLORES"] <-1708
datos$MUNICIPIO[datos$MUNICIPIO == "SAN LUIS"] <-1709
datos$MUNICIPIO[datos$MUNICIPIO == "SAYAXCHE"] <-1710
datos$MUNICIPIO[datos$MUNICIPIO == "MELCHOR DE MENCOS"] <-1711
datos$MUNICIPIO[datos$MUNICIPIO == "POPTUN"] <-1712
datos$MUNICIPIO[datos$MUNICIPIO == "LAS CRUCES"] <-1713
datos$MUNICIPIO[datos$MUNICIPIO == "EL CHAL"] <-1714
datos$MUNICIPIO[datos$MUNICIPIO == "PUERTO BARRIOS"] <-1801
datos$MUNICIPIO[datos$MUNICIPIO == "LIVINGSTON"] <-1802
datos$MUNICIPIO[datos$MUNICIPIO == "EL ESTOR"] <-1803
datos$MUNICIPIO[datos$MUNICIPIO == "MORALES"] <-1804
datos$MUNICIPIO[datos$MUNICIPIO == "LOS AMATES"] <-1805
datos$MUNICIPIO[datos$MUNICIPIO == "ZACAPA"] <-1901
datos$MUNICIPIO[datos$MUNICIPIO == "ESTANZUELA"] <-1902
datos$MUNICIPIO[datos$MUNICIPIO == "RIO HONDO"] <-1903
datos$MUNICIPIO[datos$MUNICIPIO == "GUALAN"] <-1904
datos$MUNICIPIO[datos$MUNICIPIO == "TECULUTAN"] <-1905
datos$MUNICIPIO[datos$MUNICIPIO == "USUMATLAN"] <-1906
datos$MUNICIPIO[datos$MUNICIPIO == "CABA?AS"] <-1907
datos$MUNICIPIO[datos$MUNICIPIO == "SAN DIEGO"] <-1908
datos$MUNICIPIO[datos$MUNICIPIO == "LA UNION"] <-1909
datos$MUNICIPIO[datos$MUNICIPIO == "HUITE"] <-1910
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JORGE"] <-1911
datos$MUNICIPIO[datos$MUNICIPIO == "CHIQUIMULA"] <-2001
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE LA ARADA"] <-2002
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN ERMITA"] <-2003
datos$MUNICIPIO[datos$MUNICIPIO == "JOCOTAN"] <-2004
datos$MUNICIPIO[datos$MUNICIPIO == "CAMOTAN"] <-2005
datos$MUNICIPIO[datos$MUNICIPIO == "OLOPA"] <-2006
datos$MUNICIPIO[datos$MUNICIPIO == "ESQUIPULAS"] <-2007
datos$MUNICIPIO[datos$MUNICIPIO == "CONCEPCION LAS MINAS"] <-2008
datos$MUNICIPIO[datos$MUNICIPIO == "QUETZALTEPEQUE"] <-2009
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JACINTO"] <-2010
datos$MUNICIPIO[datos$MUNICIPIO == "IPALA"] <-2011
datos$MUNICIPIO[datos$MUNICIPIO == "JALAPA"] <-2101
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO PINULA"] <-2102
datos$MUNICIPIO[datos$MUNICIPIO == "SAN LUIS JILOTEPEQUE"] <-2103
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MANUEL CHAPARRON"] <-2104
datos$MUNICIPIO[datos$MUNICIPIO == "SAN CARLOS ALZATATE"] <-2105
datos$MUNICIPIO[datos$MUNICIPIO == "MONJAS"] <-2106
datos$MUNICIPIO[datos$MUNICIPIO == "MATAQUESCUINTLA"] <-2107
datos$MUNICIPIO[datos$MUNICIPIO == "JUTIAPA"] <-2201
datos$MUNICIPIO[datos$MUNICIPIO == "EL PROGRESO"] <-2202
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CATARINA MITA"] <-2203
datos$MUNICIPIO[datos$MUNICIPIO == "AGUA BLANCA"] <-2204
datos$MUNICIPIO[datos$MUNICIPIO == "ASUNCION MITA"] <-2205
datos$MUNICIPIO[datos$MUNICIPIO == "YUPILTEPEQUE"] <-2206
datos$MUNICIPIO[datos$MUNICIPIO == "ATESCATEMPA"] <-2207
datos$MUNICIPIO[datos$MUNICIPIO == "JEREZ"] <-2208
datos$MUNICIPIO[datos$MUNICIPIO == "EL ADELANTO"] <-2209
datos$MUNICIPIO[datos$MUNICIPIO == "ZAPOTITLAN"] <-2210
datos$MUNICIPIO[datos$MUNICIPIO == "COMAPA"] <-2211
datos$MUNICIPIO[datos$MUNICIPIO == "JALPATAGUA"] <-2212
datos$MUNICIPIO[datos$MUNICIPIO == "CONGUACO"] <-2213
datos$MUNICIPIO[datos$MUNICIPIO == "MOYUTA"] <-2214
datos$MUNICIPIO[datos$MUNICIPIO == "PASACO"] <-2215
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE ACATEMPA"] <-2216
datos$MUNICIPIO[datos$MUNICIPIO == "QUESADA"] <-2217
datos$MUNICIPIO[datos$MUNICIPIO == "COLOMBA COSTA CUCA"] <- 2401
datos$MUNICIPIO[datos$MUNICIPIO == "GENOVA COSTA CUCA"] <- 2402
datos$MUNICIPIO[datos$MUNICIPIO == "LA TINTA"] <- 2403
datos$MUNICIPIO[datos$MUNICIPIO == "PACHALUN"] <- 2404
datos$MUNICIPIO[datos$MUNICIPIO == "PETATAN"] <- 2405
datos$MUNICIPIO[datos$MUNICIPIO == "QUEZALTEPEQUE"] <- 2406
datos$MUNICIPIO[datos$MUNICIPIO == "SAN BARTOLO AGUAS CALIENTES"] <- 2407
datos$MUNICIPIO[datos$MUNICIPIO == "SAN ILDEFONSO IXTAHUACAN"] <- 2408
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE EL RODEO"] <- 2409
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JOSE OJETENAM"] <- 2410
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN COMALAPA"] <- 2411
datos$MUNICIPIO[datos$MUNICIPIO == "SAN JUAN OSTUNCALCO"] <- 2412
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL DUENAS"] <- 2413
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL PETAPA"] <- 2414
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL POCHUTA"] <- 2415
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL TUCURU"] <- 2416
datos$MUNICIPIO[datos$MUNICIPIO == "SAN MIGUEL USPANTAN"] <- 2417
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO SOLOMA"] <- 2418
datos$MUNICIPIO[datos$MUNICIPIO == "SAN PEDRO YEPOCAPA"] <- 2419
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CRUZ BARILLAS"] <- 2420
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA CRUZ EL CHOL"] <- 2421
datos$MUNICIPIO[datos$MUNICIPIO == "SANTA MARIA CAHABON"] <- 2422
datos$MUNICIPIO[datos$MUNICIPIO == "SANTO TOMAS CHICHICASTENANGO"] <- 2423
datos$MUNICIPIO[datos$MUNICIPIO == "SIPACATE"] <- 2424
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 1"] <- 2425
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 2"] <- 2426
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 10"] <- 2427
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 11"] <- 2428
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 12"] <- 2429
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 13"] <- 2430
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 14"] <- 2431
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 15"] <- 2432
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 16"] <- 2433
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 17"] <- 2434
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 18"] <- 2435
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 19"] <- 2436
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 21"] <- 2437
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 24"] <- 2438
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 3"] <- 2439
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 4"] <- 2440
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 5"] <- 2441
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 6"] <- 2442
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 7"] <- 2443
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 8"] <- 2444
datos$MUNICIPIO[datos$MUNICIPIO == "ZONA 9"] <- 2445


datos$MUNICIPIO <- factor(datos$MUNICIPIO)
datos$DEPARTAMENTAL <- NULL

##Eliminacion de duplicados
datos <- read.csv("unity.csv")
require("tidyverse")
newDf <- datos[duplicated(datos),]
unique(datos)

write.csv(newDf,"./clean.csv", row.names = TRUE)

